spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:47220/railway
spring.datasource.username=root
spring.datasource.password=poleVFiMSKYbvMEauWWjSlTodeWUcRgm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=H0st3lH3lpS3cur3S3cr3tK3yTh@tIsL0ng3n0ugh2024
jwt.expiration=86400000
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=contest037@gmail.com
spring.mail.password=xbvuljeypybxwctj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.ssl.enable=true

# App name shown in emails
app.name=Hostel Help